[tool.bumpversion]
current_version = "0.2.6"
commit = true
commit_args = "--no-verify"
tag = true
tag_name = "v{new_version}"
parse = "(?P<major>\\d+)\\.(?P<minor>\\d+)\\.(?P<patch>\\d+)(\\.(?P<dev>post)\\d+\\.dev\\d+)?"
serialize = [
"{major}.{minor}.{patch}.{dev}{$PR_NUMBER}.dev{distance_to_latest_tag}",
"{major}.{minor}.{patch}"
]

[[tool.bumpversion.files]]
filename = "sord/__init__.py"
