name: Build and Release Application

on:
  push:
    tags:
      - "*"

# softprops/action-gh-release requires write permissions to the repository
permissions:
  contents: write

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, macos-14, windows-latest]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
            make install
        shell: bash
      - name: Build with PyInstaller
        run: |
            if [ "${{ matrix.os }}" = "windows-latest" ]; then
              ./venv/Scripts/activate
              PYINSTALLER="./venv/Scripts/pyinstaller.exe"
            else
              source ./venv/bin/activate
              PYINSTALLER="./venv/bin/pyinstaller"
            fi
            case "${{ matrix.os }}" in
              "macos-latest")
                $PYINSTALLER --onefile --name sord-macos-x86-64 sord/__main__.py
                ;;
              "macos-14")
                $PYINSTALLER --onefile --name sord-macos-arm64 sord/__main__.py
                ;;
              "windows-latest")
                $PYINSTALLER --onefile --name sord-windows-latest sord/__main__.py
                ;;
              *)
                $PYINSTALLER --onefile --name sord-${{ matrix.os }} sord/__main__.py
                ;;
            esac
        shell: bash
      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        with:
            files: dist/sord*
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
