name: Build and Release Application

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, macos-14, windows-latest]
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          
      - name: Install dependencies
        run: make install
        shell: bash
          
      - name: Build with PyInstaller
        run: |
          if [ "${{ matrix.os }}" = "macos-latest" ]; then
            pyinstaller --onefile --name sord-macos-x86-64 sord/__main__.py
          elif [ "${{ matrix.os }}" = "macos-14" ]; then
            pyinstaller --onefile --name sord-macos-arm64 sord/__main__.py
          elif [ "${{ matrix.os }}" = "windows-latest" ]; then
            pyinstaller --onefile --name sord-windows-latest sord/__main__.py
          else
            pyinstaller --onefile --name sord-${{ matrix.os }} sord/__main__.py
          fi
        shell: bash
      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        with:
          files: dist/sord*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
